<?php
//* Idioma: Inglés

define('hora', 'HOUR');
define('falta','ABSENT');
define('recreo','BREAK');
define('grupo','CLASS');
define('sustituye','SUBSTITUTION');
define('modifica_la_sustitucion','Modify the replacement.');
define('elije_otra_companera','Choose others workmates');
define('cerrar','Close');
define('guardar_cambios','Save changes');
define('aula','CLASSROOM');
define('asignatura','SUBJECT');
define('title','Absences Management System IES Doctor Balmis');
define('acceder','Access');
define('usuario','User');
define('contrasena','Password');
define('debe_iniciar_sesion','Welcome to "IES Doctor Balmis\' Absences Management System. It is necessary to login in order to enjoy the site functionalities. Remember that the language can be changed from the buttons "ES" (Spanish), "VA" (Valenciano) and "EN" (English).');
define('cerrar_sesion','Logout');
define('bienvenida_profesor','Welcome');
define('ausencias','Absences');
define('tu_horario','Schedule');
define('anadir_falta','ADD ABSENCE');
define('falto_todo_el_dia','I\'M ABSENT ALL THE DAY');
define('agregar_falta','ABSENCES');
define('agregar_ausencia','Add/Edit Absence');
define('agregar_ausencia_texto','Fill or change the observations and add or change a file if you wish.');
define('subir_archivo','Upload a file');
define('observaciones','COMMENTS');
define('sin_observaciones','No comments.');
define('descargas','Downloads');
define('modificar','Modify');
define('opciones','OPTIONS');
define('anadir_archivo','Ad a new file.');
define('subiendo_archivo','Uploading file. The windows will be close alone when done.');
define('ya_tiene_un','You already have a ');
define('fichero','file');
define('reemplazar','You can replace it by selecting a new file or delete it. Click to delete:');
define('eliminar_falta','Are you sure you want to delete the absence?');
define('lunes','Monday');
define('martes','Tuesday');
define('miercoles','Wednesday');
define('jueves','Thursday');
define('viernes','Friday');
define('sabado','Saturday');
define('domingo','Sunday');
define('historico_faltas','Absents history');
define('title_historico_faltas','Absents history');
define('faltas','Absents ');
define('dia','Day');
define('profesor','teacher');
define('falta_hora','Is absent at time');
define('observaciones_min','Comments');
define('falta_todo_dia','Add all day absent');
define('falto_varios_dias','Add several days absent');
define('confirmar_falto_todo_dia','Are you absent all day?');
define('dia_pasado','You can\'t add absents in a past day');
define('fecha_inicio','Start data');
define('fecha_fin','End date');
define('falta_varios_dias','Add several days absent');
define('fake_cod_profesor','Modify other teacher');
define('selecciona_profesor','Select a teacher who add and delete absences.');
define('estas_modificando','You are modifying ');
define('volver_a_mi','Back to me');
?>