<?php
//* Idioma: Español

define('hora', 'HORA');
define('falta','FALTA');
define('recreo','RECREO');
define('grupo','GRUPO');
define('sustituye','LO SUSTITUYE');
define('modifica_la_sustitucion','Modifica la sustitución');
define('elije_otra_companera','Elige a otr@(s) compañer@(s)');
define('cerrar','Cerrar');
define('guardar_cambios','Guardar los cambios');
define('aula','AULA');
define('asignatura','ASIGNATURA');
define('title','Gestión de faltas IES Doctor Balmis');
define('acceder','Acceder');
define('usuario','Usuario');
define('contrasena','Contraseña');
define('debe_iniciar_sesion','Bienvenido al sistema de gestión de faltas del Instituto Público Doctor Balmis. Es necesario que inicie sesión para acceder a las funcionalidades del sitio. Recuerde que puede cambiar el idioma desde los botones "ES" (castellano), "VA" (valenciano), "EN" (inglés).');
define('cerrar_sesion','Cerrar sesión');
define('bienvenida_profesor','Bienvenda');
define('ausencias','Ausencias');
define('tu_horario','Tu horario');
define('anadir_falta','AÑADIR FALTA');
define('falto_todo_el_dia','FALTO TODO EL DÍA');
define('agregar_falta','FALTAS');
define('agregar_ausencia','Agregar/editar ausencia');
define('agregar_ausencia_texto','Rellena o cambia las observaciones y añade o cambia un archivo si lo deseas.');
define('subir_archivo','Subir archivo');
define('observaciones','OBSERVACIONES');
define('sin_observaciones','Sin observaciones.');
define('descargas','Descargas');
define('modificar','Modificar');
define('opciones','OPCIONES');
define('anadir_archivo','Añadir un archivo nuevo.');
define('subiendo_archivo','Subiendo archivo. La ventana se cerrará automáticamente cuando termine.');
define('ya_tiene_un','Ya tiene un ');
define('fichero','fichero');
define('reemplazar','Lo puede reemplazar seleccionando un fichero nuevo o borrarlo. Haga click aquí para borrarlo:');
define('eliminar_falta','¿Estás seguro de que quieres eliminar la falta?');
define('lunes','Lunes');
define('martes','Martes');
define('miercoles','Miércoles');
define('jueves','Jueves');
define('viernes','Viernes');
define('sabado','Sábado');
define('domingo','Domingo');
define('historico_faltas','Histórico de faltas');
define('title_historico_faltas','Histórico faltas');
define('faltas','Faltas ');
define('dia','Día');
define('profesor','profesor');
define('falta_hora','Falta a la hora');
define('observaciones_min','Observaciones');
define('falta_todo_dia','Añadir falta todo el día');
define('falto_varios_dias','Añadir faltas varios días');
define('confirmar_falto_todo_dia','¿Va a faltar todo el día?');
define('dia_pasado','No puede agregar faltas a un día pasado');
define('fecha_inicio','Fecha de inicio');
define('fecha_fin','Fecha de fin');
define('falta_varios_dias','Añadir falta de varios días');
define('fake_cod_profesor','Modificar otro profesor');
define('selecciona_profesor','Selecciona un profesor al que añadir faltas y borrarlas.');
define('estas_modificando','Estás modificando a ');
define('volver_a_mi','Volver a mí');
define('bd_problem','Hay un problema en la conexión con la base de datos. Consulta con el administrador.');

?>
