<?php
//* Idioma: Valenciano

define('hora', 'HORA');
define('falta','FALTA');
define('recreo','ESBARJO');
define('grupo','GRUP');
define('sustituye','HO SUBSTITUEIX');
define('modifica_la_sustitucion','Modifica la substitució');
define('elije_otra_companera','Tria a un altre(s) company(s)');
define('cerrar','Tancar');
define('guardar_cambios','Guardar els canvis');
define('aula','AULA');
define('asignatura','ASSIGNATURA');
define('title','Gestió de faltes IES Doctor Balmis');
define('acceder','Accedir');
define('usuario','Usuari');
define('contrasena','Contrasenya');
define('debe_iniciar_sesion','Benvingut al sistema de gestió de faltes de l\'Institut Públic Doctor Balmis. És necessari que iniciï sessió per accedir a les funcionalitats del lloc. Recordi que pot canviar l\'idioma des dels botons "ÉS" (castellà), "VA" (valencià), "EN" (anglès).');
define('cerrar_sesion','Tancar sessió');
define('bienvenida_profesor','Benvingut');
define('ausencias','Absències');
define('tu_horario','El teu horari');
define('anadir_falta','AFEGIR FALTA');
define('falto_todo_el_dia','MANCAT TOT EL DIA');
define('agregar_falta','FALTES');
define('agregar_ausencia','Agregar/editar absència');
define('agregar_ausencia_texto','Farcida o canvia les observacions i afegeix o canvia un arxiu si ho desitges.');
define('subir_archivo','Pujar arxiu');
define('observaciones','OBSERVACIONS');
define('sin_observaciones','Sin observaciones..');
define('descargas','Descàrregues');
define('modificar','Modificar');
define('opciones','OPCIONS');
define('anadir_archivo','Afegir un arxiu nou.');
define('subiendo_archivo','Pujant arxiu. La finestra es tancarà automàticament quan acabi.');
define('ya_tiene_un','Ja té un ');
define('fichero','fitxer');
define('reemplazar','Ho pot reemplaçar seleccionant un fitxer nou o esborrar-ho. Faci clic aquí para esborrar-ho:');
define('eliminar_falta','Estàs segur que vols eliminar la falta?');
define('lunes','Dilluns');
define('martes','Dimarts');
define('miercoles','Dimecres');
define('jueves','Dijous');
define('viernes','Divendres');
define('sabado','Dissabte');
define('domingo','Domingo');
define('historico_faltas','Històric de faltes');
define('title_historico_faltas','Històric faltes');
define('faltas','Faltes ');
define('dia','Dia');
define('profesor','professor');
define('falta_hora','Falta a la hora');
define('observaciones_min','Observacions');
define('falta_todo_dia','Afegir falta tot el dia');
define('falto_varios_dias','Afegir faltes diversos dies');
define('confirmar_falto_todo_dia','Va a faltar tot el dia?');
define('dia_pasado','No pot agregar faltes a un dia passat');
define('fecha_inicio','Data de inici');
define('fecha_fin','Data de fi');
define('falta_varios_dias','Afegir falta de varis dies');
define('fake_cod_profesor','Modificar un altre professor');
define('selecciona_profesor','Selecciona un professor al que afegir faltes i esborrar-les.');
define('estas_modificando','Estàs modificant a ');
define('volver_a_mi','De tornada a mi');
define('bd_problem','Hay un problema en la conexión con la base de datos. Consulta con el administrador.');
?>
